title: Chakshu Gureja # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
 Contact 📞
  If you are looking forward to work with me, Feel free to contact me through
  
  <a href="https://www.linkedin.com/in/chakshu-gureja-5b6236229/"><img align="left" alt="Chakshu Gureja| Linkedin" width="40px" src="https://media-exp1.licdn.com/dms/image/C560BAQHaVYd13rRz3A/company-logo_200_200/0/1638831589865?e=2147483647&v=beta&t=Zq1zixRFUNMSm2Ldgu_hcJAYTL1gWG3VHKXO4kf9lDQ" /></a>
 
 <a href="mailto:2001chakshugureja02@gmail.com"><img align="left" alt="Chakshu Gureja| Email" width="40px" src="https://storage.googleapis.com/gweb-uniblog-publish-prod/images/Gmail.max-1100x1100.png" /></a>

 
  <a href="https://www.instagram.com/chakshu2001/"><img align="left" alt="Chakshu Gureja| Instagram " width="40px" src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Instagram_logo_2016.svg/800px-Instagram_logo_2016.svg.png" /></a>
