theme: jekyll-theme-minimal
title: Chakshu Gureja
logo: "/IMG_8360.jpg?raw=true" 
description: >
   <p style="font-size:20px"><i><b> Contact📞 </b> </i></p>
   If you are looking forward to work with me, Feel free to text me at 6475519947 or via
   <br><br>
   <a href="https://www.linkedin.com/in/chakshu-gureja-5b6236229/"><img align="left" alt="Chakshu Gureja| Linkedin" width="50px" src="https://media-exp1.licdn.com/dms/image/C560BAQHaVYd13rRz3A/company-logo_200_200/0/1638831589865?e=2147483647&v=beta&t=Zq1zixRFUNMSm2Ldgu_hcJAYTL1gWG3VHKXO4kf9lDQ" /></a> &nbsp <a href="mailto:2001chakshugureja02@gmail.com"><img align="left" alt="Chakshu Gureja| Email" width="50px" src="https://storage.googleapis.com/gweb-uniblog-publish-prod/images/Gmail.max-1100x1100.png" /></a> &nbsp <a href="https://www.instagram.com/chakshu2001/"><img align="left" alt="Chakshu Gureja| Instagram " width="50px" src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Instagram_logo_2016.svg/800px-Instagram_logo_2016.svg.png" /></a>
 
 
